import type { Plan } from "@/lib/plan-schema";

export const samplePlan: Plan = {
  title: "Napa Weekend, made easy",
  summary:
    "A relaxed two-night group escape with one focused wine day, generous buffers, and dinners close to home base.",
  location: "Napa Valley, California",
  dateLabel: "Fri, Sep 18 – Sun, Sep 20",
  partySize: 10,
  currency: "USD",
  budgetLabel: "$1,500 per person",
  estimatedTotalPerPerson: 1375,
  days: [
    {
      label: "Friday",
      date: "September 18",
      items: [
        {
          id: "sample-1",
          time: "4:00 PM",
          title: "Arrivals & house check-in",
          type: "accommodation",
          description: "Settle in, stock the kitchen, and leave room for late arrivals.",
          location: "Yountville area",
          costPerPerson: 400,
          travelMinutes: 0,
          status: "selected",
          verification: "suggested",
          bookingUrl: null,
        },
        {
          id: "sample-2",
          time: "7:30 PM",
          title: "Lively group dinner",
          type: "meal",
          description: "A welcoming first-night dinner within a short ride of the house.",
          location: "Yountville",
          costPerPerson: 95,
          travelMinutes: 8,
          status: "needs-booking",
          verification: "suggested",
          bookingUrl: null,
        },
      ],
    },
    {
      label: "Saturday",
      date: "September 19",
      items: [
        {
          id: "sample-3",
          time: "9:30 AM",
          title: "Private driver pickup",
          type: "transportation",
          description: "One driver for the day keeps the group together and the route simple.",
          location: "House pickup",
          costPerPerson: 145,
          travelMinutes: 0,
          status: "needs-booking",
          verification: "suggested",
          bookingUrl: null,
        },
        {
          id: "sample-4",
          time: "10:30 AM",
          title: "Winery tasting",
          type: "activity",
          description: "A relaxed 90-minute tasting with enough time to enjoy the property.",
          location: "St. Helena corridor",
          costPerPerson: 95,
          travelMinutes: 24,
          status: "needs-booking",
          verification: "suggested",
          bookingUrl: null,
        },
        {
          id: "sample-5",
          time: "12:30 PM",
          title: "Long lunch",
          type: "meal",
          description: "A casual lunch near the afternoon stop, with a 30-minute buffer built in.",
          location: "St. Helena",
          costPerPerson: 65,
          travelMinutes: 12,
          status: "idea",
          verification: "suggested",
          bookingUrl: null,
        },
        {
          id: "sample-6",
          time: "3:00 PM",
          title: "Second tasting or outdoor activity",
          type: "activity",
          description: "Keep this flexible: choose one more tasting or swap in something outdoors.",
          location: "Rutherford area",
          costPerPerson: 90,
          travelMinutes: 14,
          status: "idea",
          verification: "suggested",
          bookingUrl: null,
        },
        {
          id: "sample-7",
          time: "7:45 PM",
          title: "Celebration dinner",
          type: "meal",
          description: "The main dinner of the weekend, after a generous reset at the house.",
          location: "Napa",
          costPerPerson: 140,
          travelMinutes: 18,
          status: "needs-booking",
          verification: "suggested",
          bookingUrl: null,
        },
      ],
    },
  ],
  budget: [
    { category: "Stay", total: 4000, perPerson: 400 },
    { category: "Transportation", total: 1450, perPerson: 145 },
    { category: "Food & drinks", total: 3900, perPerson: 390 },
    { category: "Activities", total: 2200, perPerson: 220 },
    { category: "Buffer", total: 2200, perPerson: 220 },
  ],
  considerations: [
    "Confirm the final headcount before booking group experiences.",
    "Live venue details, prices, hours, and availability still need verification.",
  ],
};
